In [1]:
import numpy as np

In [3]:
np.random.random()

0.07040400806139879

In [6]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [10]:
np.random.uniform(1,100)

15.528833190894192

In [11]:
np.random.uniform(1,100,10)

array([10.14152088, 19.43976093, 35.21051198, 40.27997995, 54.34285667,
       42.50025693, 68.83673054, 21.24077272, 87.9336262 ,  3.71137173])

In [12]:
np.random.uniform(1,100,10).reshape(5,2)

array([[67.37628351, 42.31317543],
       [56.31029302, 14.89830692],
       [20.61204742, 80.2737123 ],
       [96.857896  , 32.02899364],
       [69.53993895, 87.76252608]])

In [16]:
np.random.randint(2,10)

7

In [18]:
np.random.randint(2,10,6)

array([8, 9, 5, 8, 7, 3])

In [19]:
np.random.randint(2,10,6).reshape(3,2)

array([[3, 5],
       [6, 2],
       [3, 5]])

In [20]:
a = np.random.randint(2,10,6)

In [21]:
a

array([6, 4, 6, 2, 7, 5])

In [22]:
np.max(a)

7

In [23]:
np.min(a)

2

In [24]:
np.argmax(a)

4

In [25]:
a[np.argmax(a)]

7

In [27]:
np.argmin(a)

3

In [26]:
a[np.argmin(a)]

2

In [28]:
a = np.random.randint(1,10,6)
a

array([3, 1, 5, 3, 8, 8])

In [29]:
a[a%2==1] = 0
a

array([0, 0, 0, 0, 8, 8])

In [31]:
b = np.random.randint(1,50,6)
b

array([27, 26, 41, 23, 10,  4])

In [34]:
np.where(b%2==1,0,b)

array([ 0, 26,  0,  0, 10,  4])

In [35]:
c = np.random.randint(1,50,10)
c

array([40, 24, 37, 28, 38, 20, 39,  9, 33, 35])

In [38]:
c = np.sort(c)
c

array([ 9, 20, 24, 28, 33, 35, 37, 38, 39, 40])

In [39]:
np.percentile(c,25)

25.0

In [40]:
np.percentile(c,50)

34.0

In [41]:
np.percentile(c,100)

40.0

In [42]:
np.percentile(c,99.8)

39.982