## creating numpy/n-d arrays

In [220]:
import numpy as np

In [221]:
arr1 = np.array([1,2,3,4,5])

In [222]:
arr1

array([1, 2, 3, 4, 5])

In [223]:
type(arr1)

numpy.ndarray

In [224]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [225]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
arr3 = np.zeros((2,3))

In [227]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [228]:
arr4 = np.ones((3,3))

In [229]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [230]:
arr5 = np.identity(5)

In [231]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [232]:
arr6 = np.arange(5,16,2)

In [233]:
arr6

array([ 5,  7,  9, 11, 13, 15])

In [234]:
arr7 = np.linspace(10,20,10)

In [235]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [236]:
arr8 = arr7.copy()

In [237]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [238]:
arr1.shape

(5,)

In [239]:
arr2.shape

(2, 3)

In [240]:
arr1.ndim

1

In [241]:
arr2.ndim

2

In [242]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [243]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [244]:
arr9.shape

(2, 2, 2)

In [245]:
arr9.ndim

3

In [246]:
arr1.size

5

In [247]:
arr9.size

8

In [248]:
arr9.itemsize

4

In [249]:
arr8.itemsize

8

In [250]:
arr8.dtype

dtype('float64')

In [251]:
arr9.dtype

dtype('int32')

In [252]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [253]:
lista = range(100)
arr11 = np.arange(100)

In [254]:
import sys

In [255]:
print(sys.getsizeof(87)*len(lista))

2800


In [256]:
print(arr11.itemsize * arr11.size)

400


In [257]:
import time

In [258]:
x = range(1000000)
y = range(1000000,2000000)

start_time = time.time()

c = [ x+y for x,y in zip(x,y) ]

print(time.time()-start_time)

0.1596064567565918


In [259]:
a = np.arange(1000000)
b = np.arange(1000000,2000000)

start_time = time.time()

d = a+b

print(time.time()-start_time)

0.0030252933502197266


In [260]:
arr12 = np.arange(24)

In [261]:
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [262]:
arr12.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [263]:
arr1

array([1, 2, 3, 4, 5])

In [264]:
arr1[2]

3

In [265]:
arr1[-1]

5

In [266]:
arr1[2:4]

array([3, 4])

In [267]:
arr12 = arr12.reshape(6,4)

In [268]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [269]:
arr12[2]

array([ 8,  9, 10, 11])

In [270]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [271]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [272]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [273]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [274]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [275]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [276]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [277]:
arr13 = np.array([1,2,3,4,5,6])
arr14 = np.array([4,5,6,7,8,9])

In [278]:
arr13 - arr14

array([-3, -3, -3, -3, -3, -3])

In [279]:
arr13 * arr14

array([ 4, 10, 18, 28, 40, 54])

In [280]:
arr13 * 2

array([ 2,  4,  6,  8, 10, 12])

In [281]:
arr14 > 6

array([False, False, False,  True,  True,  True])

In [282]:
arr15 = np.arange(6).reshape(2,3)
arr16 = np.arange(6,12).reshape(3,2)

In [283]:
arr15.dot(arr16)

array([[ 28,  31],
       [100, 112]])

In [284]:
arr1.dot(arr3)

ValueError: shapes (5,) and (2,3) not aligned: 5 (dim 0) != 2 (dim 0)

In [ ]:
arr2

In [ ]:
arr2.max()

In [ ]:
arr2.min()

In [ ]:
arr12

In [ ]:
arr12.min(axis=0)

In [ ]:
arr12.min(axis=1)

In [ ]:
arr12.sum()

In [ ]:
arr12.sum(axis=0)

In [ ]:
arr12.sum(axis=1)

In [ ]:
arr12.mean()

In [ ]:
arr12.std()

In [ ]:
np.median(arr12)

In [ ]:
np.sin(arr12)

In [ ]:
np.exp(arr12)

In [ ]:
arr12

In [ ]:
arr12.ndim

In [ ]:
arr12.ravel()

In [ ]:
arr12.transpose()

In [ ]:
arr1 = np.arange(6,12).reshape(2,3)

In [ ]:
arr1

In [ ]:
arr2 = np.arange(12,18).reshape(2,3)

In [ ]:
arr2

In [ ]:
np.hstack((arr1,arr2))

In [ ]:
np.vstack((arr1,arr2))

In [ ]:
arr1

In [ ]:
np.hsplit(arr1,3)

In [ ]:
np.vsplit(arr1,2)

### Fancy Indexing

In [ ]:
arr12

In [ ]:
arr12[[0,2,4]]

### Indexing with boolean arrays

In [ ]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr

In [ ]:
arr[0]

In [ ]:
arr[0][2]

In [ ]:
# boolean array

arr>50

In [ ]:
# indexing using boolean array / filtering

arr[arr>50]

In [ ]:
arr[(arr>50) & (arr%2!=0)]

In [ ]:
arr[(arr>50) & (arr%2!=0)]=0

In [ ]:
arr

### Plotting graphs using Numpy

In [ ]:
x = np.linspace(-40,40,100)

In [ ]:
x

In [ ]:
x.size

In [ ]:
y = np.sin(x)

In [ ]:
y

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.plot(x,y)

In [ ]:
y = x*x+2*x+6

In [ ]:
plt.plot(x,y)

### Broadcasting

In [ ]:
# If x=m and y=n, operation will take place

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1,a2)

a1+a2

In [ ]:
# If x=1 and y=n then also operation will take place (same dimension)

a3 = np.arange(3).reshape(1,3)
a4 = np.arange(12).reshape(4,3)

print(a3,a4)

a3+a4

In [ ]:
# If x=1 and y!=n then operation will not take place

a5 = np.arange(3).reshape(1,3)
a6 = np.arange(16).reshape(4,4)

print(a5,a6)

a5+a6

In [ ]:
# If x=1 and n=1 then y==m, operation to take place

a7 = np.arange(3).reshape(1,3)
a8 = np.arange(3).reshape(3,1)

print(a7,a8)

a7+a8

In [ ]:
# If x=1 and y=1, then the operation will take place no matter what

a9 = np.arange(1).reshape(1,1)
a10 = np.arange(20).reshape(4,5)

print(a9)
print(a10)

a9+a10

In [ ]:
# If they are of different dimensions

a11 = np.arange(4)
a12 = np.arange(20).reshape(5,4)

print(a11)
print(a12)

a11+a12